Repository hmcts/idam-testing-support-api, pull requests merged in 2023-09, with the labels that each got.

#297 Nightly dev
  build.gradle
Labels: ns:idam, prd:idam, rel:idam-testing-support-api-pr-297

#300 SIDM-8904 fix serenity
  build.gradle
  src/functionalTest/java/uk/gov/hmcts/cft/idam/testingsupportapi/UserApiIntegrationTest.java
Labels: ns:idam, prd:idam, rel:idam-testing-support-api-pr-300

#324 Remove dependabot
  .github/dependabot.yml
Labels: ns:idam, prd:idam, rel:idam-testing-support-api-pr-324
